# Run `conda-env create -f environment.yml`
name: mapclassify
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - geopandas
  - ipywidgets
  - libpysal
  - matplotlib
  - jupyter
  - jupyterlab
  - nbconvert
  - networkx
  - palettable
  - seaborn
  - pip:
    - git+https://github.com/pysal/mapclassify.git@main
